# Generated by Django 6.0.5 on 2026-06-03 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('logs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_name', models.CharField(choices=[('brute_force', 'Brute Force Attack'), ('after_hours_login', 'After Hours Login'), ('port_scan', 'Port Scan Detected'), ('multiple_failures', 'Multiple Auth Failures')], max_length=50)),
                ('severity', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], max_length=20)),
                ('status', models.CharField(choices=[('open', 'Open'), ('investigating', 'Investigating'), ('resolved', 'Resolved'), ('false_positive', 'False Positive')], default='open', max_length=20)),
                ('source_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('username', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField()),
                ('triggered_at', models.DateTimeField(auto_now_add=True)),
                ('analyst_notes', models.TextField(blank=True)),
                ('related_logs', models.ManyToManyField(blank=True, to='logs.logentry')),
            ],
            options={
                'ordering': ['-triggered_at'],
            },
        ),
    ]
