# Generated by Django 6.0.5 on 2026-06-03 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('source', models.CharField(choices=[('auth', 'Auth Log'), ('firewall', 'Firewall Log'), ('web', 'Web Server Log')], max_length=20)),
                ('source_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('username', models.CharField(blank=True, max_length=100, null=True)),
                ('action', models.CharField(max_length=100)),
                ('details', models.TextField(blank=True)),
                ('raw_line', models.TextField()),
                ('ingested_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
